### ISSUE TITLE
THP - Maybe?

### ISSUE THREAD

**Issue by waynekearns** [Atemu/nixos-config#1]
Hey, not a criticism, but something that you might consider if you plan on doing high performance DB or NoSQL data processing on a machine, THP has to be disabled because the memory reorg kills the performance of those applications. (MySQL, MariaDB, Elastic, Splunk, etc etc)

Feel free to close this issue, just figured I'd leave you a note about that section of common.nix. 

Thank you very much for making your repo public. It was very helpful.

**Comment by Atemu** [comment]
From what I gathered at the time I added that flag, lots of information on THP performance is out of date or for poorly made applications which I don't plan on using anyways.

Also note that the THP support and THP defrag are separate options. THP defrag only happens on MADV_HUGEPAGE regions by default (though maybe I should switch that to `defer+madvise`)

Glad it was of help :)  
I'd recommend you do the same ;)

**Comment by waynekearns** [comment]
I'll look into it. At one point the defrag option fixed some of the problems but not others. It seems obnoxious that applications that are moving huge swaths of data around don't play nice with THP. 

In the past madvise broke them in fantastical ways.

I'll give it a whirl again. Things do change. Have a great weekend!
